" use strict " ;
const axios = require("axios");
// const apikey = ; // your api key to the api generated by the website
const getWeather = location => {
    return new Promise(async(resolve, reject) => {
        try { 
            const weatherConditions = await axios.get( 
            // write your api address access here , for instance : "http://api.apixu.com/v1/forecast.json",
                {
                params : {
                            key : apikey ,
                            q : location ,
                            days : 3
                        }
                });

            resolve(weatherConditions.data) // returns back the results to the chatbot
            }
        catch ( error ) {reject(error); }
  }) ;
 }

 module.exports = getWeather ;